version: 2
jobs:
  test:
    docker:
        - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - run: bundle install
      - run: rubocop --only Lint/Debugger
      - run: rspec ./spec
workflows:
  version: 2
  test:
    jobs:
      - test
