version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - run: bundle install
      - run: rubocop --only Lint/Debugger
      - run: rspec ./spec
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
              gem build ddtrace_method_wrapper.gemspec
              gem push "ddtrace-method-wrapper-$(echo $CIRCLE_TAG | sed 's/^v//').gem"
workflows:
  version: 2
  test:
    jobs:
      - test
  publish-tag:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - publish:
          context: rubygems-credentials
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
